# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180119_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
